name: Build Travete Focus APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar dependências do Ubuntu
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

      - name: Instalar Ferramentas de Build
        run: |
          python -m pip install --upgrade pip
          pip install cython virtualenv
          pip install "buildozer==1.5.0"

      - name: Limpar e Compilar APK
        run: |
          buildozer android clean
          buildozer android debug
        env:
          PLAYSTORE_BUILD: "False"

      - name: Guardar o APK pronto
        uses: actions/upload-artifact@v4
        with:
          name: TraveteFocus-APK
          path: bin/*.apk
